### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isError' of undefined

### ISSUE THREAD

**Issue by rioki** [ivangabriele/atom-tfs#1]
[Enter steps to reproduce below:]

Packages -> TFS -> Get Latest Version

**tf.exe Version**: 10.0.30319.1
**tfpt.exe Version**: 2010

**Atom Version**: 1.7.2
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-tfs](https://github.com/ivangabriele/atom-tfs) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'isError' of undefined

```
At /C:/Users/adfase1/.atom/packages/atom-tfs/lib/tfs/get.coffee:14

TypeError: Cannot read property 'isError' of undefined
    at get (file:///C:/Users/adfase1/.atom/packages/atom-tfs/lib/tfs/get.coffee:12:14)
    at Object.module.exports.AtomTfs.tfsExec (file:///C:/Users/adfase1/.atom/packages/atom-tfs/lib/atom-tfs.coffee:30:5)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-tfs:get (file:///C:/Users/adfase1/.atom/packages/atom-tfs/lib/atom-tfs.coffee:9:80)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\adfase1\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\adfase1\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\adfase1\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\adfase1\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\adfase1\AppData\Local\atom\app-1.7.2\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -3:23.1.0 core:delete (atom-text-editor.editor.is-focused)
  2x -3:22.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:21.6.0 core:delete (atom-text-editor.editor.is-focused)
  3x -3:17.8.0 core:select-left (atom-text-editor.editor.is-focused)
     -3:15 core:delete (atom-text-editor.editor.is-focused)
  2x -3:14.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:28.6.0 atom-tfs:get (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-tfs, v0.4.0
atom-tfs-auto, v0.2.0
keyboard-localization, v1.4.18
minimap, v4.23.1

# Dev
No dev packages
```

**Comment by abyrne85** [comment]
+1
