### ISSUE TITLE
Uncaught TypeError: callback is not a function

### ISSUE THREAD

**Issue by roberto-slopez** [ivangabriele/atom-tfs#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [atom-tfs](https://github.com/ivangabriele/atom-tfs) package, v0.4.0

### Stack Trace

Uncaught TypeError: callback is not a function

```
At C:\Users\desar\.atom\packages\atom-tfs\node_modules\tfs\lib\tfs\checkin.js:31

TypeError: callback is not a function
    at newCallback (C:\Users\desar\.atom\packages\atom-tfs\node_modules\tfs\lib\tfs\checkin.js:31:7)
    at ChildProcess.<anonymous> (C:\Users\desar\.atom\packages\atom-tfs\node_modules\tfs\lib\utils\tf.js:49:9)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

### Commands

```
     -9:37.2.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  9x -9:35.6.0 core:save (atom-text-editor.editor.is-focused)
  4x -7:16.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -7:15 core:delete (atom-text-editor.editor.is-focused)
 42x -7:14.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -7:12.1.0 core:delete (atom-text-editor.editor.is-focused)
 17x -7:11.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:44.2.0 atom-tfs:checkin (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "pigments",
      "autocomplete-modules",
      "auto-detect-indentation",
      "language-javascript-jsx",
      "linter-package-json-validator",
      "language-javascript-semantic",
      "language-js-specs",
      "linter-js-yaml",
      "language-babel",
      "redux-devtools"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "dracula-ui",
      "dracula-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.9
atom-beautify, vundefined
atom-jshint, v2.0.0
atom-react-native-css, v1.1.2
atom-symfony2, v0.2.1
atom-tfs, v0.4.0
autocomplete-elixir, v1.5.13
build-elixir, v0.6.0
color-picker, v2.1.1
data-atom, v0.20.4
docblockr, v0.7.3
dracula-theme, v1.2.7
dracula-ui, v0.3.0
elixir-cmd, v0.2.9
emmet, v2.4.3
git-checkout, v0.3.2
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
jshint, v1.8.5
language-asp, v1.0.0
language-aspx, v0.4.0
language-elixir, v0.13.1
language-twig, v1.6.3
language-vb, v0.1.0-pre1
linter, v1.11.4
linter-jshint, v2.1.0
local-history, v3.3.0
markdown-themeable-pdf, vundefined
merge-conflicts, v1.4.4
navigation-history, v0.1.8
pdf-view, v0.50.0
quick-query-mssql, v0.1.2
react-snippets, v0.4.2
redux-snippets, v0.2.2
seti-icons, v1.2.1
source-preview-react, v0.2.0
symfony-snippets, v0.3.0
wakatime, v6.0.5
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by kwiss** [comment]
+1

**Comment by Reminouche** [comment]
Same problem here

**Comment by AndreyShpilevoy** [comment]
+1
